### ISSUE TITLE
We ain't got no code

### ISSUE THREAD

**Issue by Sam-Kaminetzky** [Sam-Kaminetzky/UW-418-MMAP-EMAP-RFID#1]
There ain't no code. Let's fix

**Comment by codit04** [comment]
I am an absolute beginner . Is this supposed to be a joke or is actually an issue?

**Comment by Sam-Kaminetzky** [comment]
> I am an absolute beginner . Is this supposed to be a joke or is actually an issue?

Joke issue. This is the very beginning of a fairly mundane and arcane project.
